services:
  - type: web
    name: n8n-affiliate-automation
    env: node
    plan: starter
    buildCommand: |
      npm install -g pnpm@10.12.1
      pnpm install --frozen-lockfile --filter=!@n8n/chat
      npm install -g ./packages/cli
    startCommand: n8n start --port=$PORT
    envVars:
      - key: NODE_VERSION
        value: 22.18.0
      - key: PNPM_VERSION
        value: 10.12.1
      - key: PORT
        value: 10000
