services:
  - type: web
    name: n8n
    env: node
    plan: starter
    buildCommand: |
      set -eux
      export PNPM_HOME="$HOME/.local/share/pnpm"
      export PATH="$PNPM_HOME/bin:$PATH"
      curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION=10.12.1 sh -
      pnpm --version
      pnpm add -g n8n@1.81.1
      # Verify n8n is installed
      which n8n
      n8n --version
    startCommand: |
      export PNPM_HOME="$HOME/.local/share/pnpm"
      export PATH="$PNPM_HOME/bin:$PATH"
      exec n8n start --port=$PORT
    envVars:
      - key: NODE_VERSION
        value: 22.18.0
