services:
  - type: web
    name: n8n-affiliate-automation
    env: node
    plan: starter
    buildCommand: |
      corepack enable
      corepack prepare pnpm@10.12.1 --activate
      pnpm install --frozen-lockfile
    startCommand: pnpm start --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 22.18.0
      - key: PNPM_VERSION
        value: 10.12.1
